job.type: train
job.device: cpu
dataset.name: toy
model: complex

train:
  type: negative_sampling
  optimizer: dist_adagrad
  optimizer_args:
    lr: 0.6
    #weight_decay: 0.4e-7
  loss: kl
  loss_arg: 2.0  # margin
  batch_size: 20

lookup_embedder.dim: 100
lookup_embedder.sparse: True
lookup_embedder.regularize_args.weighted: True
lookup_embedder.regularize_weight: 0.0

complex:
  entity_embedder:
    regularize_weight: 0.0
  relation_embedder:
    regularize_weight: 0.0

negative_sampling:
  shared: True
  num_samples:
    s: 3
    p: 0
    o: -1  # means: as s
  filtering:
    s: False
    o: False
    p: False
    implementation: fast_if_available
